CC = i686-elf-gcc
LD = i686-elf-ld
AS = nasm
OBJCOPY = i686-elf-objcopy
PYTHON = python3
ISO = genisoimage
CFLAGS = -m32 -std=gnu99 -ffreestanding -fno-pie -fno-pic -fno-stack-protector -fno-builtin -Wall -Wextra -O2 -I.
BUILD = build
OBJECTS = $(BUILD)/kernel_entry.o $(BUILD)/kernel.o $(BUILD)/screen.o $(BUILD)/keyboard.o $(BUILD)/fs.o $(BUILD)/timer.o

.PHONY: all clean

all: $(BUILD)/directos.img $(BUILD)/directos.bin $(BUILD)/directos.iso

$(BUILD):
	mkdir -p $(BUILD)

$(BUILD)/boot.bin: boot.asm | $(BUILD)
	$(AS) -f bin $< -o $@

$(BUILD)/kernel_entry.o: kernel_entry.asm | $(BUILD)
	$(AS) -f elf32 $< -o $@

$(BUILD)/%.o: %.c | $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/kernel.elf: $(OBJECTS) linker.ld
	$(LD) -m elf_i386 -T linker.ld -o $@ $(OBJECTS)

$(BUILD)/kernel.bin: $(BUILD)/kernel.elf
	$(OBJCOPY) -O binary $< $@

$(BUILD)/directos.img: $(BUILD)/boot.bin $(BUILD)/kernel.bin build_image.py
	$(PYTHON) build_image.py $(BUILD)/boot.bin $(BUILD)/kernel.bin $@

$(BUILD)/directos.bin: $(BUILD)/directos.img
	cp $< $@

$(BUILD)/iso-root/directos.img: $(BUILD)/directos.img
	mkdir -p $(BUILD)/iso-root
	cp $< $@

$(BUILD)/directos.iso: $(BUILD)/iso-root/directos.img
	$(ISO) -o $@ -V DIRECTOS -b directos.img -c boot.catalog $(BUILD)/iso-root

clean:
	rm -rf $(BUILD)
